### ISSUE TITLE
Auto generate the properties file needed by Accumulo ITs.

### ISSUE THREAD

**Issue by busbey** [apache/fluo-uno#196]
It'd be nice to easily use a uno created Accumulo cluster to run the version of the accumulo ITs that talk to a cluster.

That'd be easier if uno filled out [a properties file for the configuration settings the ITs need](https://github.com/apache/accumulo/blob/1.9/TESTING.md#configuration-for-standalone-clusters).

**Comment by ctubbsii** [comment]
That link is broken.

**Comment by ctubbsii** [comment]
This would be a good feature for Muchos also.

**Comment by busbey** [comment]
Link fixed. My apologies I thought I had corrected it when copying from my TODO list.
