### ISSUE TITLE
Properties read from uno home

### ISSUE THREAD

**Issue by milleruntime** [apache/fluo-uno#210]
I had a copy of accumulo.propties in my uno home directory, thinking it was safely copied there but this file was overriding properties I thought were being set in accumulo-home/conf/accumulo.properties.  I am not sure what is putting uno home on the classpath but this defintely caused me a headache.  Maybe at the least we can warn if we find multiple accumulo.properties files on the classpath.

**Comment by ctubbsii** [comment]
Should be fixed with apache/accumulo#859 and apache/accumulo#864
