### ISSUE TITLE
Grammar correction in README.md file

### ISSUE THREAD

**Issue by kpm1985** [apache/fluo-uno#216]
Currently the third sentence under the first heading reads:

> 

 Uno makes it easy to setup a dev stack running Fluo or Accumulo, it also makes it easy clear your data and setup your dev stack again. 

> 

Just needs to have grammar fixed so it reads "it also makes it easy **to** clear .."

**Comment by kpm1985** [comment]
Here is a pull for it: https://github.com/apache/fluo-uno/pull/217
I think I goofed and created a branch on the apache repo, which I did not mean to do, I noticed my blunder and removed it. I apologize for that.

**Comment by ctubbsii** [comment]
@kpm1985 No need to create an issue if you're going to create a PR. The PR serves as its own issue. :smiley_cat:

**Comment by kpm1985** [comment]
@ctubbsii Noted, thank you!
