### ISSUE TITLE
Instance name uno does not exist in zookeeper

### ISSUE THREAD

**Issue by KangXuechao** [apache/fluo-uno#224]
fluo-uno]$ ./bin/uno ashell
Loading configuration from /data0/fluo-uno/install/accumulo-2.0.0-alpha-2/conf/accumulo-client.properties
2019-05-26 01:00:07,973 [start.Main] ERROR: Thread 'shell' died.
java.lang.RuntimeException: Instance name uno does not exist in zookeeper. Run "accumulo org.apache.accumulo.server.util.ListInstances" to see a list.
	at org.apache.accumulo.core.clientImpl.ClientContext.getInstanceID(ClientContext.java:389)
	at org.apache.accumulo.shell.Shell.printInfo(Shell.java:623)
	at org.apache.accumulo.shell.Shell.start(Shell.java:527)
	at org.apache.accumulo.shell.Shell.execute(Shell.java:513)
	at org.apache.accumulo.start.Main.lambda$execKeyword$0(Main.java:129)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ctubbsii** [comment]
@KangXuechao Did you run `./bin/uno setup accumulo` first?

**Comment by rcarterjr** [comment]
> fluo-uno]$ ./bin/uno ashell
> Loading configuration from /data0/fluo-uno/install/accumulo-2.0.0-alpha-2/conf/accumulo-client.properties
> 2019-05-26 01:00:07,973 [start.Main] ERROR: Thread 'shell' died.
> java.lang.RuntimeException: Instance name uno does not exist in zookeeper. Run "accumulo org.apache.accumulo.server.util.ListInstances" to see a list.
> at org.apache.accumulo.core.clientImpl.ClientContext.getInstanceID(ClientContext.java:389)
> at org.apache.accumulo.shell.Shell.printInfo(Shell.java:623)
> at org.apache.accumulo.shell.Shell.start(Shell.java:527)
> at org.apache.accumulo.shell.Shell.execute(Shell.java:513)
> at org.apache.accumulo.start.Main.lambda$execKeyword$0(Main.java:129)
> at java.lang.Thread.run(Thread.java:748)

These commands fixed that error for me (Ubuntu):
cat <<EOF | sudo tee -a /etc/security/limits.conf > /dev/null
   hard nproc 65536
   soft nproc 65536
   hard nofile 65536
   soft nofile 65536
   EOF

then run:

./bin/uno fetch accumulo
./bin/uno setup accumulo

**Comment by ctubbsii** [comment]
Glad you fixed it!
