### ISSUE TITLE
ZK update broke previous versions of ZK

### ISSUE THREAD

**Issue by milleruntime** [apache/fluo-uno#246]
With the update to Zk 3.5+ in #239 , the previous version of Zk 3.4 no longer works due to the changes in binary paths. There is a workaround to change the name of the tar ball but this is cumbersome if switching to Accumulo version 1.9.x

**Comment by ctubbsii** [comment]
I don't think Uno needs to support older versions of ZooKeeper any more. ZooKeeper is currently in process of discussing making the 3.4 line end-of-life, and it hasn't been actively maintained in awhile. The last release from 3.4 was over a year ago, and only released because of a critical security bug.

**Comment by ctubbsii** [comment]
Uno can patch Accumulo 1.9 config files to add the ZooKeeper lib directory, if necessary to make 1.9 work on newer ZooKeeper versions.

**Comment by milleruntime** [comment]
> Uno can patch Accumulo 1.9 config files to add the ZooKeeper lib directory, if necessary to make 1.9 work on newer ZooKeeper versions.

If that works, that would be great.  I just think we still need to be bale to run 1.9 in Uno.

**Comment by ctubbsii** [comment]
It should be a simple matter of adding the lib dir to Accumulo's `conf/accumulo-site.xml` in the `general.classpaths` property, if anybody wants to try.

**Comment by milleruntime** [comment]
> It should be a simple matter of adding the lib dir to Accumulo's `conf/accumulo-site.xml` in the `general.classpaths` property, if anybody wants to try.

It seems to be more that that.  The start-all script in 1.9 is searching for the jar.  I am getting this error during initialize:
```
A Zookeeper JAR was not found in /home/mpmill4/workspace/uno/install/apache-zookeeper-3.5.7-bin.
Please check ZOOKEEPER_HOME, either globally or in accumulo-env.sh.
[ERROR] Error occurred at /home/mpmill4/workspace/uno/bin/impl/run/accumulo.sh:34 command: "$ACCUMULO_HOME"/bin/start-all.sh
```
The start-all.sh has a specific spot its looking for:
```
ZOOKEEPER_VERSION=$(find -L $ZOOKEEPER_HOME -maxdepth 1 -name "zookeeper-[0-9]*.jar" | head -1)
if [ -z "$ZOOKEEPER_VERSION" ]; then
   echo "A Zookeeper JAR was not found in $ZOOKEEPER_HOME."
   echo "Please check ZOOKEEPER_HOME, either globally or in accumulo-env.sh."
   exit 1
fi
```

**Comment by ctubbsii** [comment]
Ugh. `start-all.sh`. This is what happens when we try to hard-code in deployment assumptions into our scripts. Uno might have to patch `start-all.sh` to work with newer ZK with Accumulo 1.9. It might a simple matter of using `-maxdepth 2`, but I'd have to try.

**Comment by milleruntime** [comment]
Setting the maxdepth to 2 worked.
