### ISSUE TITLE
Update Accumulo install scripts

### ISSUE THREAD

**Issue by milleruntime** [apache/fluo-uno#271]
Update the install per latest changes in Accumulo to cluster start stop scripts: https://github.com/apache/accumulo/commit/03d76769366971ebacb575f7c5e6c962ddbea29c

**Comment by milleruntime** [comment]
Here is the error when trying to run `uno setup accumulo`:
<pre>
sed: can't read /home/mike/workspace/uno/install/accumulo-2.1.0-SNAPSHOT/conf/tservers: No such file or directory
[ERROR] Error occurred at /home/mike/workspace/uno/bin/impl/install/accumulo.sh:53 command: $SED "s#localhost#$UNO_HOST#" "$conf/tservers"
</pre>

**Comment by Manno15** [comment]
It appears the changes to the `create-config`  accumulo command is causing this specific issue. https://github.com/dlmarion/accumulo/blob/c5f49fad7edaed391ee9b274c083bc41ade23eab/assemble/bin/accumulo-cluster#L444-L445.
