### ISSUE TITLE
`--no-deps` arg is at unexpected position for run/accumulo.sh

### ISSUE THREAD

**Issue by Manno15** [apache/fluo-uno#275]
Currently, the command `uno setup accumulo --no-deps` will fail setup due to the `--no-deps` arg being in a different position than expected for `run/accumulo.sh`. The script expects $1 (like how it is inside `install/accumulo.sh`) but this script reads the position of `--no-deps` at $2. The simple fix is to change `run/accumulo.sh` to expect the arg to be in $2 but I suspect there might be a bug as to why each script reads the position as something different. A small test is below to visually show the issue,

Here is an example of the command being run with $1 being printed to console: 

```
 jeffrey@groot: uno setup accumulo --no-deps
Setting up accumulo (detailed logs in /home/jeffrey/git/fluo-uno/install/logs/setup)...
what is at arg1 in install/accumulo.sh: --no-deps
Installing Apache Accumulo 2.1.0-SNAPSHOT at /home/jeffrey/git/fluo-uno/install/accumulo-2.1.0-SNAPSHOT
what is at arg1 at run/accumulo.sh: accumulo
Setup of accumulo failed!
```

**Comment by milleruntime** [comment]
Since we have scripts calling other scripts, it may be less confusing to just refactor the scripts to not use shift. Otherwise, we may have to do lots of checking of the parameters to figure out if they were shifted or not.

**Comment by Manno15** [comment]
Apparently the issue in this case is the extra "$component" added in the script call: https://github.com/apache/fluo-uno/blob/fc519d6b4a407575f3ce73ad28d33869a98021f9/bin/impl/util.sh#L102

Removing that fixed the position issue.

**Comment by ctubbsii** [comment]
@milleruntime wrote:
> Since we have scripts calling other scripts, it may be less confusing to just refactor the scripts to not use shift. Otherwise, we may have to do lots of checking of the parameters to figure out if they were shifted or not.

`shift` merely strips `$1` out of the functions `$@` argument list, so that `$@` now contains only the stuff after the first argument. This is done correctly in both those methods, where `$component` is read from `$1`, and then `shift` is called to pass the remaining `$@` to the next script.

@Manno15 wrote:
> Apparently the issue in this case is the extra "$component" added in the script call:
> 
> https://github.com/apache/fluo-uno/blob/fc519d6b4a407575f3ce73ad28d33869a98021f9/bin/impl/util.sh#L102
> 
> Removing that fixed the position issue.

I think that's the right fix. I think this was a bug that was introduced when the run command was refactored from a single script, prior to which we had to pass the component so that single script could know which one to run. Now that they are running their own `$component.sh`, it shouldn't be necessary to pass the component anymore. However, each possible `impl/run/*.sh` should be checked to make sure they process their parameters correctly and aren't relying on that extra `$component` being present.

**Comment by Manno15** [comment]
> I think that's the right fix. I think this was a bug that was introduced when the run command was refactored from a single script, prior to which we had to pass the component so that single script could know which one to run. Now that they are running their own $component.sh, it shouldn't be necessary to pass the component anymore. However, each possible impl/run/*.sh should be checked to make sure they process their parameters correctly and aren't relying on that extra $component being present.

I will double check them and make sure the performance tests are running as well. Will have a pr up shortly.

**Comment by milleruntime** [comment]
> shift merely strips $1 out of the functions $@ argument list, so that $@ now contains only the stuff after the first argument. This is done correctly in both those methods, where $component is read from $1, and then shift is called to pass the remaining $@ to the next script.

But how does the second script know if $1 was stripped out or not?

**Comment by Manno15** [comment]
Ran into a build issue with accumulo-testing while trying to test this change, created an issue here: https://github.com/apache/accumulo-testing/issues/169

**Comment by ctubbsii** [comment]
> > shift merely strips $1 out of the functions $@ argument list, so that $@ now contains only the stuff after the first argument. This is done correctly in both those methods, where $component is read from $1, and then shift is called to pass the remaining $@ to the next script.
> 
> But how does the second script know if $1 was stripped out or not?

`$@` is just a variable name, local to the function, or if outside a function, local to the containing script. It represents the args passed to the function (or script), just as in `public static void main(String[] args)`, `args` represents the array passed to it.
`shift` just modifies the array by moving the pointer to the first element to the next element, effectively creating a new array starting at the next element and continuing until the end of the original array. When it is placed as an argument for another script, the script initializes its own `$@` variable from the parameters passed to it.

For example:

```bash
# let $@ be the array ("item1" "item2" "item3")
./otherscript.sh "item0" "$@" "item4"
# other script would create its own $@ that looks like ("item0" "item1" "item2" "item3" "item4")
shift 2 # drop the first two items from this script's $@
./otherscript.sh "item0" "$@" "item4"
# other script would now create its own $@ that looks like ("item0" "item3" "item4")
```

**Comment by milleruntime** [comment]
> $@ is just a variable name, local to the function, or if outside a function, local to the containing script.

Ah OK, I was thinking it was local to the process. Thanks for the explanation.
